### PR TITLE
Add kubernetes subproject template files and update `OWNERS` 

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull request completes a task under https://github.com/jpbetz/auger/issues/42 to add kubernetes subproject template files from https://github.com/kubernetes/kubernetes-template-project.

Additionally I've updated `OWNERS` based on the discussion in https://github.com/jpbetz/auger/issues/42 so that post repository move new approvers will be able to manage the repository.

I believe this is the final work required before the repository can be donated.

### CODE REVIEW

**Comment by jmhbnz** [comment]
cc @jpbetz, @siyuanfoundation, @wenjiaswe


Additionally - @jberkus can you please confirm the mechanics / process we should follow to initiate the repository move if this pull request is completed?

**Comment by wzshiming** [comment]
Ohhhhh, will this project be moved to k-sigs? I thought this project was no longer maintained, I referenced it and refactored the code to make it a kubelet-like subcommand to manipulate etcd data directly. If this project will be moved to sigs, I thought I might be able to re-add the work I've done here? 

I would also like to be involved in the development of further features for this project.

https://github.com/kubernetes-sigs/kwok/pull/859

**Comment by jberkus** [comment]
@jmhbnz yeah, I'll ask what the next step is.

**Comment by jberkus** [comment]
I need to file an issue, I have the info I need for it.  However, we need to merge this PR first.

**Comment by jpbetz** [comment]
> I need to file an issue, I have the info I need for it. However, we need to merge this PR first.

Sounds like I might need to jump in for a step here. I'll merge this now.

**Pull request merged**
